package api

import (
	"errors"
	"strconv"
	"strings"
	"testing"
)

// ⚠️ THE TOKENS IN THIS TABLE ARE NOT INVENTED. Everything under "a rendered
// listing, piped" is a real word from a real `investviews geo hexes` run —
// header, availability sentence, cursor hint and cost line — measured against
// the live API on 2026-09-13. They are what `--h3 -` was being handed, and
// they are why this parser cannot be a digit test: "3", "8" and "500" are
// perfectly good decimal numbers taken straight out of "3 cell(s)", "at res 8"
// and "500 cell(s)".
func TestParseH3Cell(t *testing.T) {
	cases := []struct {
		name  string
		token string
		want  bool
	}{
		// the two documented forms
		{"decimal id, as every endpoint emits", "613498076398616575", true},
		{"decimal id, res 8 in València", "613498079194120191", true},
		{"canonical H3 string", "8839540ad1fffff", true},
		{"canonical H3 string, upper case", "8839540AD1FFFFF", true},
		{"surrounding whitespace is not a value", "  613498076398616575\n", true},

		// a rendered listing, piped
		{"a geo_id from the header", "R344953", false},
		{"a place name from the header", "València", false},
		{"a level, bracketed", "(city,", false},
		{"a country, bracketed", "es)", false},
		{"an em dash", "—", false},
		{"the cell COUNT from the header", "3", false},
		{"the word cell(s)", "cell(s)", false},
		{"the word at", "at", false},
		{"the RESOLUTION from the header", "8", false},
		{"a page size from the header", "500", false},
		{"a cursor from the more-cells hint", "eyJrIjoxfQ", false},
		{"the word cost:", "cost:", false},
		{"FREE from the cost line", "FREE", false},

		// near misses
		{"empty", "", false},
		{"zero", "0", false},
		{"negative", "-613498076398616575", false},
		{"above uint64", "99999999999999999999999", false},
		{"0x prefix", "0x8839540ad1fffff", false},
		{"an H3 index with the wrong mode bits", "1229782938247303441", false},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := ParseH3Cell(tc.token)
			if tc.want != (err == nil) {
				t.Fatalf("ParseH3Cell(%q) error = %v, want accepted = %v", tc.token, err, tc.want)
			}
		})
	}
}

// Both documented forms name the SAME cell, so they must parse to the same
// index — otherwise "accepted" would mean two different things.
func TestParseH3CellAgreesAcrossTheTwoForms(t *testing.T) {
	decimal, err := ParseH3Cell("613498079267520511")
	if err != nil {
		t.Fatalf("decimal: %v", err)
	}
	// The pair the contract itself prints for this cell.
	canonical, err := ParseH3Cell("8839540ad1fffff")
	if err != nil {
		t.Fatalf("canonical: %v", err)
	}
	if decimal != canonical {
		t.Errorf("the two forms of one cell parsed to %d and %d", decimal, canonical)
	}
}

// The message has to name the token: a piped listing fails on its first word,
// and which word it was is what tells the caller which pipe produced it.
func TestValidateH3CellsNamesTheOffendingTokenAndTheFix(t *testing.T) {
	err := ValidateH3Cells([]string{"613498076398616575", "cell(s)", "613498076398616576"})
	if err == nil {
		t.Fatal("a non-cell token must be refused")
	}
	var valErr *ValidationError
	if !errors.As(err, &valErr) {
		t.Fatalf("err = %T, want *ValidationError", err)
	}
	if valErr.Parameter != "h3" {
		t.Errorf("Parameter = %q, want h3", valErr.Parameter)
	}
	for _, want := range []string{`"cell(s)"`, "cost no quota", "--ids-only"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("message does not mention %q:\n%s", want, err.Error())
		}
	}
	if ExitCode(err) != ExitError {
		t.Errorf("ExitCode = %d, want %d", ExitCode(err), ExitError)
	}
}

func TestValidateH3CellsAcceptsAWholeListOfRealCells(t *testing.T) {
	cells := []string{"613498076398616575", "613498076402810879", "8839540ad1fffff"}
	if err := ValidateH3Cells(cells); err != nil {
		t.Fatalf("ValidateH3Cells(%v) = %v", cells, err)
	}
	if err := ValidateH3Cells(nil); err != nil {
		t.Errorf("an empty list is not a bad cell: %v", err)
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// The bit layout, field by field
// ─────────────────────────────────────────────────────────────────────────────

// ⚠️ THESE CELLS ARE NOT INVENTED EITHER, AND THEY ARE NOT ALL RES 8 ON
// PURPOSE. The live API only ever emits res 8 — `geo hexes` answers every
// place at res 8 and `geo lookup` returns an h3_res of 8 — so a fixture set
// taken from it alone would leave the resolution and digit fields untested at
// fifteen of their sixteen values.
//
// The rows below were generated by an INDEPENDENT H3 implementation (the Ruby
// `h3` gem, which binds upstream h3lib) on 2026-09-14, one cell per resolution
// 0..15 for three points on three continents. The whole of IsH3Cell was also
// cross-checked against that library over 325,419 values — every base cell,
// every res-0..8 pentagon, single-bit mutations of 400 real cells, and 300,000
// random uint64s — with ZERO false rejects. A false reject is the failure that
// matters here: it would break --h3 outright, while a false accept costs one
// server 400.
//
// The two sources agree where they overlap: the res-8 Kyiv row below is the
// byte-identical id `geo lookup --lat 50.4501 --lng 30.5234` returned from
// production, and the res-8 València row is what it returned for València.
var realCellsByResolution = []struct {
	res       int
	decimal   uint64
	canonical string
	place     string
}{
	{0, 577481099093999615, "8039fffffffffff", "València"},
	{1, 581975902628347903, "81397ffffffffff", "València"},
	{2, 586476753476648959, "823957fffffffff", "València"},
	{3, 590980146945589247, "833954fffffffff", "València"},
	{4, 595483686443417599, "8439541ffffffff", "València"},
	{5, 599987280702078975, "8539540bfffffff", "València"},
	{6, 604490880061014015, "8639540afffffff", "València"},
	{7, 608994479654830079, "8739540adffffff", "València"},
	{8, 613498079194120191, "8839540a8bfffff", "València"}, // also live: geo lookup 39.4623,-0.3763
	{9, 618001678820966399, "8939540a8b7ffff", "València"},
	{10, 622505278448238591, "8a39540a8b67fff", "València"},
	{11, 627008878075580415, "8b39540a8b60fff", "València"},
	{12, 631512477702947839, "8c39540a8b603ff", "València"},
	{13, 636016077330318271, "8d39540a8b603bf", "València"},
	{14, 640519676957688727, "8e39540a8b60397", "València"},
	{15, 645023276585059220, "8f39540a8b60394", "València"},
	{0, 577023702256844799, "801ffffffffffff", "Kyiv"},
	{4, 595009771162042367, "841e63bffffffff", "Kyiv"},
	{8, 613024153737363455, "881e6384a3fffff", "Kyiv"}, // also live: geo lookup 50.4501,30.5234
	{12, 631038552245716991, "8c1e6384a2ec7ff", "Kyiv"},
	{15, 644549351127828132, "8f1e6384a2ec6a4", "Kyiv"},
	{0, 579838452023951359, "80bffffffffffff", "Sydney"},
	{4, 597818645413887999, "84be0e3ffffffff", "Sydney"},
	{8, 615833041184489471, "88be0e35cbfffff", "Sydney"},
	{12, 633847439693631999, "8cbe0e35cbad1ff", "Sydney"},
	{15, 647358238575743144, "8fbe0e35cbad0a8", "Sydney"},
	// A pentagon base cell (4). Twelve of the 122 base cells are pentagons
	// and their cells are ordinary, spendable ids — a check that treated
	// "pentagon" as "suspicious" would delete them from the map.
	{0, 576636674163867647, "8009fffffffffff", "pentagon base 4"},
	{3, 590112357393367039, "830800fffffffff", "pentagon base 4"},
	{8, 612630286812839935, "8808000001fffff", "pentagon base 4"},
	{15, 644155484202336256, "8f0800000000000", "pentagon base 4"},
}

// A real cell must be accepted in BOTH documented forms and in either case,
// and all three spellings must parse to the same index — otherwise "accepted"
// means different things on the two routes into --h3.
func TestParseH3CellAcceptsRealCellsAtEveryResolution(t *testing.T) {
	for _, c := range realCellsByResolution {
		t.Run(c.canonical, func(t *testing.T) {
			if !IsH3Cell(c.decimal) {
				t.Fatalf("res %d %s (%s) is a real cell and must be accepted", c.res, c.canonical, c.place)
			}
			for _, form := range []string{
				strconv.FormatUint(c.decimal, 10),
				c.canonical,
				strings.ToUpper(c.canonical),
			} {
				got, err := ParseH3Cell(form)
				if err != nil {
					t.Fatalf("ParseH3Cell(%q) = %v, want the cell", form, err)
				}
				if got != c.decimal {
					t.Errorf("ParseH3Cell(%q) = %d, want %d", form, got, c.decimal)
				}
			}
		})
	}
}

// Every live cell this CLI has actually been handed, straight out of the two
// endpoints that emit them. Transcribed from production on 2026-09-14: five
// places at two levels in two countries, plus a geo lookup point.
func TestParseH3CellAcceptsCellsTheLiveAPIEmitted(t *testing.T) {
	live := []string{
		"613477298412191743", "613477298456231935", "613477298464620543", // R349043 region
		"613492931231219711", "613492931237511167", "613492931239608319", // R349000 province
		"613498076398616575", "613498076402810879", "613498076568485887", // R344953 city
		"613498079194120191", // geo lookup 39.4623,-0.3763
		"613024153737363455", // geo lookup 50.4501,30.5234 (Kyiv)
	}
	if err := ValidateH3Cells(live); err != nil {
		t.Fatalf("the API's own cells must be accepted: %v", err)
	}
}

// withField replaces one field of an index, leaving every other bit alone, so
// a rejection below can only be attributed to the field that moved.
func withField(index uint64, shift, mask, value uint64) uint64 {
	return (index &^ (mask << shift)) | ((value & mask) << shift)
}

// withDigit replaces digit r (1..15) of an index.
func withDigit(index uint64, r int, value uint64) uint64 {
	return withField(index, uint64((h3MaxRes-r)*h3DigitBits), h3DigitMask, value)
}

// ⚠️ ONE FAULT PER CASE, AND EACH CASE STATES WHICH CHECK IS SUPPOSED TO CATCH
// IT. The failure mode this guards against is a case that passes for the wrong
// reason — a "malformed" id that is really being refused by the mode test.
// That is why every row carries oldCheckWouldAccept: the rows marked true are
// exactly the ids that the mode-bits-only check LET THROUGH onto the metered
// endpoint, and if a future edit narrows the check back to the mode, those
// rows fail.
func TestIsH3CellRejectsEachStructuralFaultOnItsOwn(t *testing.T) {
	// Res 8, València — the whole table below is this one cell with one
	// field changed.
	const good = uint64(613498079194120191) // 8839540a8bfffff
	if !IsH3Cell(good) {
		t.Fatalf("the fixture cell %d must be accepted, or every case below proves nothing", good)
	}

	cases := []struct {
		name                string
		index               uint64
		oldCheckWouldAccept bool
	}{
		{"bit 63, the reserved high bit, is set", good | (1 << h3HighBitShift), false},
		{"mode 0 — an index that names nothing", withField(good, h3ModeShift, h3ModeMask, 0), false},
		{"mode 2 — a directed edge, not a cell", withField(good, h3ModeShift, h3ModeMask, 2), false},
		{"mode 15 — the top of the mode field", withField(good, h3ModeShift, h3ModeMask, 15), false},

		{"mode-dependent bits set to 1", withField(good, h3ReservedShift, h3ReservedMask, 1), true},
		{"mode-dependent bits set to 7", withField(good, h3ReservedShift, h3ReservedMask, 7), true},

		{"base cell 122 — one past the last one", withField(good, h3BaseCellShift, h3BaseCellMask, 122), true},
		{"base cell 127 — the top of the field", withField(good, h3BaseCellShift, h3BaseCellMask, 127), true},

		// Digits 9..15 are above res 8 and must all be 7.
		{"unused digit 15 is 6, not 7", withDigit(good, 15, 6), true},
		{"unused digit 15 is 0, not 7", withDigit(good, 15, 0), true},
		{"unused digit 9 is 0, not 7", withDigit(good, 9, 0), true},

		// Digits 1..8 are in use and 7 never names a direction.
		{"used digit 1 is 7", withDigit(good, 1, 7), true},
		{"used digit 8 is 7", withDigit(good, 8, 7), true},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if IsH3Cell(tc.index) {
				t.Fatalf("%d (%x) is malformed and must be refused", tc.index, tc.index)
			}
			oldCheck := tc.index>>h3ModeShift == h3CellMode
			if oldCheck != tc.oldCheckWouldAccept {
				t.Errorf("the mode-bits-only check accepted = %v, want %v — this case is no "+
					"longer testing what it says it tests", oldCheck, tc.oldCheckWouldAccept)
			}
			// And it must be refused through the string route too, in
			// both documented spellings.
			for _, form := range []string{
				strconv.FormatUint(tc.index, 10),
				strconv.FormatUint(tc.index, 16),
			} {
				if _, err := ParseH3Cell(form); err == nil {
					t.Errorf("ParseH3Cell(%q) accepted a malformed id", form)
				}
			}
		})
	}
}

// ⚠️ THE ID FROM THE REVIEW FINDING. 8839540ad1ffffe differs from the real
// cell 8839540ad1fffff in ONE bit: its last unused digit is 6 rather than 7.
// It parses as hex and carries the cell mode, so the mode-bits-only check sent
// it to the METERED endpoint and paid for a server 400.
//
// The neighbour is here because the point is a one-bit difference, not a
// blocklist: the real id must still be accepted.
func TestParseH3CellRejectsAWellFormedLookingIdWithABadUnusedDigit(t *testing.T) {
	const bad = "8839540ad1ffffe"
	const good = "8839540ad1fffff"

	index, err := strconv.ParseUint(bad, 16, 64)
	if err != nil {
		t.Fatalf("the finding's id must at least parse as hex: %v", err)
	}
	if index>>h3ModeShift != h3CellMode {
		t.Fatal("the finding's id carries the cell mode; without that it proves nothing")
	}
	if _, err := ParseH3Cell(bad); err == nil {
		t.Errorf("%s has a used-digit value in an unused slot and must be refused locally", bad)
	}
	if _, err := ParseH3Cell(good); err != nil {
		t.Errorf("%s is a real cell and must still be accepted: %v", good, err)
	}
}

// ⚠️ WHAT THE CHECK DELIBERATELY DOES NOT CATCH, pinned so it cannot be
// mistaken for an oversight. Base cell 4 is a pentagon, and on a pentagon the
// first non-zero digit may not be 1 — that path does not exist on the grid.
// Ruling it out needs the pentagon table, which is where a few bit tests would
// turn into an H3 implementation, so 830840fffffffff is accepted here and
// answered 400 by the server.
//
// The trade is one wasted request against the risk of wrongly refusing a real
// cell, which would break --h3 outright. If a later change adds the pentagon
// table, this test is the one to update — and h3.go, docs/api.md and
// skills/investviews/SKILL.md all describe the residue and would need it gone.
func TestIsH3CellAcceptsTheDocumentedPentagonResidue(t *testing.T) {
	const impossiblePentagonPath = "830840fffffffff" // pentagon base 4, digit 1 = 1
	const realNeighbour = "830880fffffffff"          // the same cell with digit 1 = 2

	if _, err := ParseH3Cell(impossiblePentagonPath); err != nil {
		t.Errorf("%s is structurally well formed; the documented behaviour is to accept it "+
			"and let the server refuse it: %v", impossiblePentagonPath, err)
	}
	if _, err := ParseH3Cell(realNeighbour); err != nil {
		t.Errorf("%s is a real cell: %v", realNeighbour, err)
	}
}
